apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actualserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actualserver
    app.kubernetes.io/part-of: actual
    app: actualserver
  name: actualserver
  namespace: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: actualserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: actualserver
        app: actualserver
    spec:
      containers:
      - image: quay.io/scoheb/actual-server:1.3
        imagePullPolicy: Always
        name: container-image
        resources: {}
        ports:
          - name: http
            containerPort: 5006
        volumeMounts:
          - mountPath: /app/user-files
            name: actual-data
      volumes:
        - name: actual-data
          persistentVolumeClaim:
            claimName: actual-data
          
status: {}
---
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actualserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actualserver
    app.kubernetes.io/part-of: actual
    app: actualserver
apiVersion: v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Service
metadata:
  name: actual
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actualserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actualserver
    app.kubernetes.io/part-of: actual
    app: actualserver
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: http
  selector:
    app: actualserver
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: actual-server
  namespace: actual
  labels:
    app: actualserver
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitopsdepl-5065d421-5798-4d9c-a995-113336aef958
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actualserver
    app.kubernetes.io/part-of: actual
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: actual
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
